apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-redis-pv
  labels:
    {{- include "haddock.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.redis.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.redis.storage.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redis-pvc
  labels:
    {{- include "haddock.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
