{{- if .Values.user.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user
  labels:
    {{- include "haddock.labels" . | nindent 4 }}
    app: user-service
spec:
  replicas: {{ .Values.user.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: {{ .Values.user.image.name }}:{{ .Values.user.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 5000
{{- end }}
